version: '3.8'
services:
  mysql_db:
    image: 'mysql'
    command: '--default-authentication-plugin=mysql_native_password'
    env_file:
      - '.env'
    ports:
      - '3306:3306'
    container_name: 'mysql_db'
    volumes:
      - 'mysql_data:/var/lib/mysql'
  

  node_api:
    build: '.'
    ports:
      - '3000:3000'
    env_file:
      - '.env'
    container_name: 'node_api'
    volumes:
      - './:/app'
      - '/app/node_modules'
    depends_on:
      - mysql_db

volumes:
  mysql_data: